language: node_js
node_js:
  - '10'
services:
  - docker
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: 'MLCoCJhGN2gHCd+Ph7+WPoSYRi5raYHu0EEgWcgnIbvduarx+/sHp9LU1auKmdHs+axSIwH8FtDbgn91SSLRmbicV6MoiqUGANLNbOZ3EICSvOkx+FvXLwHdY2RvCO9Kxh/OiSNDKJLMUNidbmBGTg/x9EG/0Zf8uQwG4NwfU520MuA0Rn+Z3FkO8HB7M7THwgFcC77tRQKOv/myb/+nxa0zU7VszCAdnD4mipEeiFjiLcQGZ5A6WNWxqXBcyW6ep9ceBbvR+qax4Sj3Jds+JW/d7k6FNCGlRZHkE14/BrGHZ4DMc/eQbbmhQbGGiGY5TbPQxDo1TN5WpBXjcVAlD5bWYAkMBwAGHQM0HEK2pkBr5PbkHbU8aEiFnSQic90PLVGYTwbrg2dlCrDZSLJn/jyriD2V+vN3JuK7rf2MCHTpxkGUn+NLB/nFaUwLRtNLrXbrRHHeQYPf79Ck/zXw6XOSMJMZSdrk+SU9W/t/kcKAIkehU3RSHPEZ7VY94xLxItaoy8/NxwwdWsB8ma8KgeCs0V1JIj3cHnVXW9i/sXZpe7Lksg4ni/lfpNUuK3tqon6HopIKB4JPT+ptGf8pCs2IKocSb8anpsdmX0By9MEQV3dnmLDiHTYM71Y7Pwtt6k8FkZW4c/yW+4FpEyabwWnLRfD/UNl3cIUONRUn66k='
  secret_access_key:
    secure: 'L7zKidkJ+S5QUDsjHmjJQGIu++VIRCxHJBBPVrE0e6wYncFjXmIfxppR7PS3ybylD+PkzM+Q9kuCTN7EzziQAiqS1lTFxnhS+X25uCE4JDremMadKasEeFqOsbhddqSBm43xqQMxlpnWnggpb+gTbpZWjxVCyg53LiLOZAsP1wpRD4YYrGUS1YQ40v3JwuAmvK7j73ZAtn6x8VDpTjPEBmmTfHZjp7M8CFtYQgg7peaLm50NbRSTo5Bg/Nqw8iazgG8Fmy+E0taHQfKhPVpkk+COl5y1E2o2/ZSOsKq2DKTVwY9zqND74AdhGZGXuo2uI74zXwbWaXFartX6agbdM0Z8NH1vUUBh2KGX65kXG6AS3prRWbKsK9QE3oq0alC5zcOra56w7hdySCN2hPDgx/mxbTU88s49JwaqvEVlaawvQymxk4pSWdo5BmYn0dQLQQeNJlks7GTkyw9sydx7bqWNsrc2gMRPAxhxZpITwiH3mywGGb5OiYhw2UAlLlSdeBB7w9Jx64Mz9JU9jpivrmSQU8mEfmJAvM2tgCOnfdecblmabbtjB97hUNdzP5mCiFCkSpwIn7ylzuHUuiWiyjMEi7dzyXhFwo/8Dz95x/a/3KINZU+vCJ3018E1LMC+Jfqoh/FDHDb9bN80P73/QV+pwioaUzE1dF6qiWPlBag='
  region: eu-central-1
  app: node-typescript-test
  env: e-mzkjcpazxp
